// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOyMly4iyDVJ3j8tBwRL0sN-XIVtp4dhc',
    appId: '1:1039533109345:web:41128ec6f246c480da7a20',
    messagingSenderId: '1039533109345',
    projectId: 'qaramia-4c405',
    authDomain: 'qaramia-4c405.firebaseapp.com',
    storageBucket: 'qaramia-4c405.firebasestorage.app',
    measurementId: 'G-M8FM97ETJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU4gv9wQR4K7eXbV2-YKEk8X05i1JG_FY',
    appId: '1:1039533109345:android:64b1a34a6ab1776fda7a20',
    messagingSenderId: '1039533109345',
    projectId: 'qaramia-4c405',
    storageBucket: 'qaramia-4c405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-koaiYWvv6msycSG4spPLBhmnPyEcl28',
    appId: '1:1039533109345:ios:6c8e4ac24e8f8b70da7a20',
    messagingSenderId: '1039533109345',
    projectId: 'qaramia-4c405',
    storageBucket: 'qaramia-4c405.firebasestorage.app',
    androidClientId: '1039533109345-56cr9psv855si8v8fsskg83e5sav3oq3.apps.googleusercontent.com',
    iosClientId: '1039533109345-ppeuhg3c2oned3tk56vbrn6h0kede0k6.apps.googleusercontent.com',
    iosBundleId: 'com.qaramia.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-koaiYWvv6msycSG4spPLBhmnPyEcl28',
    appId: '1:1039533109345:ios:6c8e4ac24e8f8b70da7a20',
    messagingSenderId: '1039533109345',
    projectId: 'qaramia-4c405',
    storageBucket: 'qaramia-4c405.firebasestorage.app',
    androidClientId: '1039533109345-56cr9psv855si8v8fsskg83e5sav3oq3.apps.googleusercontent.com',
    iosClientId: '1039533109345-ppeuhg3c2oned3tk56vbrn6h0kede0k6.apps.googleusercontent.com',
    iosBundleId: 'com.qaramia.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOyMly4iyDVJ3j8tBwRL0sN-XIVtp4dhc',
    appId: '1:1039533109345:web:ee28ff8b1811334bda7a20',
    messagingSenderId: '1039533109345',
    projectId: 'qaramia-4c405',
    authDomain: 'qaramia-4c405.firebaseapp.com',
    storageBucket: 'qaramia-4c405.firebasestorage.app',
    measurementId: 'G-ZQYNT2WVGQ',
  );

}